FROM elixir:1.17.0 AS test

RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app

COPY mix.exs mix.lock ./

RUN mix do deps.get, deps.compile

COPY . .

ENV MIX_ENV=test

CMD ["mix", "test"]
